name: Update Dependency Graph

on:
  workflow_dispatch:
  push:
    branches:
      - '*''

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Build with Maven
      run: mvn clean install

    - name: Extract dependencies
      run: mvn dependency:tree -DoutputType=dot -DoutputFile=dependencies.dot

    - name: Submit dependencies to GitHub
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        curl -X POST \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          -d @dependencies.dot \
          https://api.github.com/repos/${{ github.repository }}/dependency-graph/snapshots